### ISSUE TITLE
Remove /build directory from .gitignore

### ISSUE THREAD

**Issue by gamba** [swiss/styleguide#411]
_admin.css_ references to *glyphicons-halflings-regular.woff2* but the file is missing from the repository.

**Comment by tonifisler** [comment]
The reason for this is we are currently ignoring the `/build` folder in the [`.gitgnore`] (https://github.com/swiss/styleguide/blob/master/.gitignore#L8) file, so if we forget to `$ git add -f` those files, we don't commit everything.

This should be changed, as we need to commit the built files when releasing a new version and this should be an easy process.

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-103

**Comment by desobryc** [comment]
@LeBenLeBen will this be corrected with 3.0?

**Comment by LeBenLeBen** [comment]
All the required files have been committed but the rule to ignore this folder is still present. We can change it easily for the release.

**Comment by desobryc** [comment]
That would be great, thanks!

**Comment by LeBenLeBen** [comment]
This has been fixed in release 3.0.0
